Create spec class for HA_RGW
jmolmo/ceph pull request #4
Opened 2020-10-29 17:27 UTC by adk3798

Signed-off-by: Adam King <adking@redhat.com>

NOTE: There are currently failures in the mgr tox on this branch from other commits so the unit test I've added here can't actually be tested until later. It might need some adjustment in the future but I've left it in since I think the general idea is still there.

2020-10-29 19:21 UTC, Daniel-Pivonka approved these changes
looks good as far as i can tell

2020-10-30 16:45 UTC, jmolmo approved these changes
LGTM

2020-10-30 16:53 UTC, jmolmo requested changes
After taking a look to the keepalived config .. i realize the we do not need the "keepalived_user"

2020-10-30 16:53 UTC, jmolmo commented on src/pybind/mgr/cephadm/tests/test_spec.py
> +  keepalived_user: admin
Remove this line, Not needed.

2020-10-30 16:53 UTC, jmolmo commented on src/pybind/mgr/cephadm/tests/test_spec.py
> +    assert spec.keepalived_user == "admin"
remove

2020-10-30 16:53 UTC, jmolmo commented on src/python-common/ceph/deployment/service_spec.py
> +                 keepalived_user: Optional[str] = None,
remove

2020-10-30 16:53 UTC, jmolmo commented on src/python-common/ceph/deployment/service_spec.py
> +        self.keepalived_user = keepalived_user
remove

2020-10-30 16:53 UTC, jmolmo commented on src/python-common/ceph/deployment/service_spec.py
> +                'Cannot add HA_RGW: No Keepalived User specified')
remove

2020-11-03 10:21 UTC, jmolmo approved these changes

2020-11-03 10:21 UTC, merged